# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc3bc1f1bdb98306744af3d1d63cef381c1b81720bc26a8f616daaf8d11dc67fe970b334e02cab5a9555199b3d449f149c2e7fd4a83a512fc92ce29633e1f00e

test:
  secret_key_base: 21ef24fbd089f6cc0bedbcbef6c64f759bde4ce826c6f37bd8603bec455d1bb08bd8c29df892787bc2609083c33a6e9add0f5258e5ae670f78c15a17fd06233d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
